from dataclasses import dataclass, field
from typing import Any


CONNECTOR_REGISTERED = "CONNECTOR_REGISTERED"
CONNECTOR_STARTED = "CONNECTOR_STARTED"
CONNECTOR_STOPPED = "CONNECTOR_STOPPED"
CONNECTOR_HEALTH_CHANGED = "CONNECTOR_HEALTH_CHANGED"
CONNECTOR_DISCOVERED = "CONNECTOR_DISCOVERED"
CONNECTOR_FAILED = "CONNECTOR_FAILED"
CONNECTOR_OBSERVATION = "CONNECTOR_OBSERVATION"
CONNECTOR_EVIDENCE = "CONNECTOR_EVIDENCE"
CONNECTOR_WARNING = "CONNECTOR_WARNING"
CONNECTOR_ERROR = "CONNECTOR_ERROR"


@dataclass
class ConnectorEventData:
    connector_id: str
    event_type: str
    payload: Any = None
    metadata: dict = field(default_factory=dict)
